### ISSUE TITLE
IceCap missing dependency?

### ISSUE THREAD

**Issue by michaelBenin** [nanopx/gulp-esdoc#10] opened 2016-05-01 15:55 UTC
var logger = new Logger("IceCap");
             ^

TypeError: Logger is not a function

**Comment by arcticShadow** [comment] 2016-05-04 20:53
I'm experiencing this too. 

'Logger' is actually an instance of 'color-logger' and as far as i can tell it is actually there.

**Comment by arcticShadow** [comment] 2016-05-04 20:56
also - ice-cap and color-logger and made by the same author as esdoc, and are not dependencies of this project, but of esdoc

**Comment by arcticShadow** [comment] 2016-05-04 21:29
This has been fixed in esdoc - even though there is no mention of it. (ESDoc has bumped dependency on ice-cap to 0.0.4, where the issue is resolved) so in theory this module need sto bump to esdoc 0.4.7

**Comment by nanopx** [comment] 2016-08-18 07:22
Closing this for now, should be solved #13

**Closed as completed by nanopx** 2016-08-18 07:22 UTC
